In [3]:
import numpy as np

# Problem 1

Create a two dimensional array (A) containg the integer numbers from 0 to 31, organized into a 8 x 4 matrix (row ordered)

In [4]:
A= np.arange(32).reshape(8,4)
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


Write the commands for printing:
* The elements along the first column
* The elements on the 2nd and 3rd row (all the columns)
* The last column in reverse order

In [13]:
print(A[:,0])
print(A[(1,2),:])
print(A[:,-1][::-1])
A.shape[0]

[ 0  4  8 12 16 20 24 28]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[31 27 23 19 15 11  7  3]


8

Use np.concatenate (or np.vstack, np.hstack) for creating:
* an array equal to A plus one row of ones appended at the end
* an array equal to A with two columns of zeros appended at the end

In [53]:

A_plus_one = np.concatenate((A,np.ones((1,A.shape[1]))),axis=0)
print(A_plus_one)
A_plus_one = np.concatenate((A,np.ones((A.shape[0],2))),axis=1)
print(A_plus_one)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [16. 17. 18. 19.]
 [20. 21. 22. 23.]
 [24. 25. 26. 27.]
 [28. 29. 30. 31.]
 [ 1.  1.  1.  1.]]
[[ 0.  1.  2.  3.  1.  1.]
 [ 4.  5.  6.  7.  1.  1.]
 [ 8.  9. 10. 11.  1.  1.]
 [12. 13. 14. 15.  1.  1.]
 [16. 17. 18. 19.  1.  1.]
 [20. 21. 22. 23.  1.  1.]
 [24. 25. 26. 27.  1.  1.]
 [28. 29. 30. 31.  1.  1.]]


Calculate (and print):
* The sum of the elements of the array A 
* The sum of the rows of A
* The sum of the columns of A
* The averages of the 8 rows of A
* The averages of the 4 columsn of A

In [58]:
print(np.sum(A,axis=None))

print(np.sum(A,axis=0))

print(np.sum(A,axis=1))

print(np.mean(A,axis=0))

print(np.mean(A,axis=1))

496
[112 120 128 136]
[  6  22  38  54  70  86 102 118]
[14. 15. 16. 17.]
[ 1.5  5.5  9.5 13.5 17.5 21.5 25.5 29.5]


# Problem 2

The array X defined below includes 10^6 random numbers with uniform distribution in the interval \[0,1\] organized as a (1000 x 1000) matrix.
Define 3 different functions for calculating the averages of the columns of X, with the following characteristics:
* function1 uses a cycle and built-in methods (sum) for calculating the averages
* function2 uses a cycle along the columns and np.mean for calculating the averages
* function3 uses np.mean with the axis parameter (and no cycle)

Use the %timeit directive to estimate the perfomances of the three functions

In [13]:
X = np.random.uniform(low = 0, high = 1, size = (1000,1000))

In [17]:
def mean_columns_method_one(X):
    mean = []
    for column in X.T:
        mean.append(sum(column)/len(column))
    return mean

def mean_columns_method_two(X):
    mean = []
    for column in X.T:
        mean.append(np.mean(column))
    return mean

def mean_columns_method_three(X):
    M = np.mean(X,axis=1)


In [18]:
%timeit mean_columns_method_one(X)

66.7 ms ± 271 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [20]:
%timeit mean_columns_method_two(X)

6.56 ms ± 87 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [21]:
%timeit mean_columns_method_three(X)

327 µs ± 503 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)


# Problem 3

Given the arrays A and b defined below:
* sum the vector b to all the rows of A, and print the result
* sum the vector b to all the column of A, and print the result

In [41]:
import numpy as np
A = np.random.uniform(low = 0, high = 10, size = (3,3))
b = np.array([1,2,3])
print(A)
print(b)

[[5.36221094 0.87662214 9.34391714]
 [6.11076112 3.05653529 8.38096712]
 [0.51647673 6.66273724 8.08098956]]
[1 2 3]


In [44]:
A + b.reshape((1,-1))
A + b.reshape((-1,1))

array([[ 6.36221094,  1.87662214, 10.34391714],
       [ 8.11076112,  5.05653529, 10.38096712],
       [ 3.51647673,  9.66273724, 11.08098956]])

Given the arrays A and B defined below, using arythmetic operations and ufuncs:
* calculate their scalar product
* calculate their norms


In [59]:
A = np.array([1,4,0,2])
B = np.array([2,3,-1,-1])

In [64]:
print(A @ B)
print(np.linalg.norm(A))
print(np.linalg.norm(B))

12
4.58257569495584
3.872983346207417


Considering the same arrays A and B, calculate a 4 x 4 array with the element i,j equal to the product between the element i of A and the element j of B

In [98]:
print(A.reshape((-1,1)) * B.reshape((1,-1)))

[[ 2  3 -1 -1]
 [ 8 12 -4 -4]
 [ 0  0  0  0]
 [ 4  6 -2 -2]]


The array A defined below includes data for a set of samples (the rows), where each sample is characterized by three features (the columns). Calculate the norm of all the samples

In [124]:
n = 10
np.random.seed(1)
A = np.random.uniform(low = 0, high = 1, size = (n,3))
print(A)

[[4.17022005e-01 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]
 [1.86260211e-01 3.45560727e-01 3.96767474e-01]
 [5.38816734e-01 4.19194514e-01 6.85219500e-01]
 [2.04452250e-01 8.78117436e-01 2.73875932e-02]
 [6.70467510e-01 4.17304802e-01 5.58689828e-01]
 [1.40386939e-01 1.98101489e-01 8.00744569e-01]
 [9.68261576e-01 3.13424178e-01 6.92322616e-01]
 [8.76389152e-01 8.94606664e-01 8.50442114e-02]
 [3.90547832e-02 1.69830420e-01 8.78142503e-01]]


In [125]:
np.linalg.norm(A,axis=1)

array([0.83233091, 0.34852359, 0.55814829, 0.96725037, 0.90202053,
       0.96736979, 0.83674641, 1.23088415, 1.25523366, 0.89526639])

Calculate an array with the distances between all the samples in A and the sample b

In [126]:
b = np.random.uniform(low = 0, high = 1, size = 3)
print(b)

[0.09834683 0.42110763 0.95788953]


In [127]:
print(
    
        np.sum( 
           (
               A - 
               b.reshape(1,-1)
           )**2
           , axis=1)
    **.5
)

[1.05281425 0.93062209 0.57296951 0.51804087 1.04208933 0.69763668
 0.27603197 0.9159002  1.26151105 0.27021356]


Given the two random arrays defined below, calculate the matrix product taking advantage of broadcasting rules.

In [128]:
n = 4
m = 3
A = np.random.randint(low = 0, high = 5, size = (n,m))
B = np.random.randint(low = 0, high = 5, size = (m,n))

In [129]:
np.sum(A.reshape((A.shape[0],A.shape[1],1))*B.reshape((1, B.shape[0],B.shape[1])), axis = 1)
np.dot(A,B)

array([[12, 18, 23, 13],
       [ 5, 11, 13,  9],
       [16, 16, 34, 16],
       [ 7,  9,  7,  3]])

# Problem 4

Define a function that takes as input an (n x 3) array, with n being the number of samples and 3 the number of dimensions, and that it returns an (n x n) array  with element i,j equal to the distance between sample i and sample j. First, do it using any cycle you want. Then, try to get rid of the cycles, until none is left. Compare the performaces of the different implementations, using random data sets of different size.

In [131]:
n = 100
A = np.random.uniform(low = 0, high = 1, size = (n,3))

In [145]:
def method_1(A,n):
    D = np.empty((A.shape[0],A.shape[0]))
    for outer_iterator in range(A.shape[0]):
        for inner_iterator in range(A.shape[0]):
            D[outer_iterator,inner_iterator] = np.sum( (A[outer_iterator,:] - A[inner_iterator,:])**2) **.5
            
def method_2(A):
    D = np.empty((A.shape[0],A.shape[0]))
    for iterator in range(A.shape[0]):
        D[iterator,:] = np.sum( (A - A[iterator,:].reshape(1,-1)) **2) **.5      

def method_3(A):
    return np.sum(
        (A.reshape((A.shape[0],A.shape[1],1))
         -A.transpose().reshape((1,A.shape[1],A.shape[0])))**2, axis = 1)**0.5
            
%timeit method_1(A,n)
%timeit method_2(A)
%timeit method_3(A)


190 ms ± 1.44 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
2.89 ms ± 28.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
749 µs ± 1.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


# Problem 5

Given the (n x 4) random array defined below, with n being the number of samples, and 4 the number of dimensions, count how many samples have:
* positive values for the first dimension
* positive values for the first two dimensions and negative values for the remaining ones
* second dimension higher than first dimension
* sum between the first two dimensions higher than sum between the second two dimensions

In [147]:
import numpy as np
n = 10
np.random.seed(1)
A = np.random.uniform(low = -1, high = 1, size = (n,4))
print(A)

[[-0.16595599  0.44064899 -0.99977125 -0.39533485]
 [-0.70648822 -0.81532281 -0.62747958 -0.30887855]
 [-0.20646505  0.07763347 -0.16161097  0.370439  ]
 [-0.5910955   0.75623487 -0.94522481  0.34093502]
 [-0.1653904   0.11737966 -0.71922612 -0.60379702]
 [ 0.60148914  0.93652315 -0.37315164  0.38464523]
 [ 0.7527783   0.78921333 -0.82991158 -0.92189043]
 [-0.66033916  0.75628501 -0.80330633 -0.15778475]
 [ 0.91577906  0.06633057  0.38375423 -0.36896874]
 [ 0.37300186  0.66925134 -0.96342345  0.50028863]]


In [160]:
print(np.sum(A[:,0]>0))
print(np.sum((A[:,0] > 0) & (A[:,1] > 0) & (A[:,2] < 0) & (A[:,3] < 0)))
print(np.sum((A[:,(0,1)]>0) & (A[:,(2,3)]<0)))
print(np.sum( A[:,0]+A[:,1] > A[:,2]+A[:,3]))


4
1
8
8


# Problem 6

Given the random array A defined below, select and print:
* all the columns for the rows with even index
* the 3rd column for the rows with even index
* the columns with odd index for the rows with even index (be carefull about broadcasting)
* the positive elements of A
* all the columns for the rows with a positive element on the first column
* the 4th column for the rows with a positive element on the first column

In [205]:
n = 5
m = 6
np.random.seed(1)
A = np.random.randint(low = -10, high = 10, size = (n,m))
print(A)

[[ -5   1   2  -2  -1   1]
 [ -5   5 -10   6  -9   2]
 [ -3   3  -4   8  -5   8]
 [  1   0   4   8  -6  -1]
 [  7 -10   3  -1  -1  -3]]


In [176]:
print(A[ [i % 2 == 0 for i in range(A.shape[0] )],:])

[[5 8 9 5 0 0]
 [5 2 4 2 4 7]
 [9 9 7 6 9 1]]


In [177]:
print(A[ [i % 2 == 0 for i in range(A.shape[0] )],3])

[5 2 6]


In [202]:
print(np.array( [i for i in range(A.shape[0]) if i % 2 == 0]).reshape(-1,1))
print(np.array( [i for i in range(A.shape[1]) if i % 2 == 1]).reshape(1,-1))

print(A[ np.array( [i for i in range(A.shape[0]) if i % 2 == 0]).reshape(-1,1),np.array( [j for j in range(A.shape[1]) if j % 2 == 1]).reshape(1,-1)])

[[0]
 [2]
 [4]]
[[1 3 5]]
[[8 5 0]
 [2 2 7]
 [9 6 1]]


In [203]:
print(A[A>0])

[5 8 9 5 1 7 6 9 2 4 5 2 4 2 4 7 7 9 1 7 6 9 9 7 6 9 1]


In [207]:
# all the columns for the rows with a positive element on the first column
print(A[A[:,0] > 0])

[[  1   0   4   8  -6  -1]
 [  7 -10   3  -1  -1  -3]]


In [208]:
#  the 4th column for the rows with a positive element on the first column
print(A[A[:,0] > 0][:,3])

[ 8 -1]
